"use strict";

const command = (name, usage, description, extra = {}) => ({ name, usage, description, ...extra });

const commands = [
  command("init", "init [options]", "Initialize Cortex Agent."),
  command("add", "add <platform...>", "Add platform integrations."),
  command("remove", "remove <platform...>", "Remove platform integrations."),
  command("list", "list", "Show available and installed platforms."),
  command("export-anchor", "export-anchor [--format markdown|json] [--project <path>] [--name <name>]", "Emit the cross-tool recognition anchor (markdown or JSON) so any AI tool can identify this project as cortex-agent-managed and load AGENTS.md + .agent/. Markdown is the default; JSON is for tools that ingest structured memory (e.g. Pi agent)."),
  command("upgrade", "upgrade [options]", "Add missing Agent files without overwriting local content."),
  command("update", "update [options]", "Add files and safely refresh unmodified managed scripts."),
  command("local-publish-validate", "local-publish-validate [options]", "Local pack + local install + optional target upgrade. NEVER publishes to npm; uses volta file: protocol. For RC dogfooding and cross-project template validation. See .agent/workflows/local-publish-validate.md.", { mode: "local_validation", implemented: true, requires: ["volta", "npm"] }),
  command("track", "track", "Enable Git tracking for .agent."),
  command("untrack", "untrack", "Disable Git tracking for .agent."),
  command("link-global", "link-global", "Link global ~/.agent configuration."),
  command("doctor", "doctor [options]", "Check setup health."),
  command("team", "team <init|status|install|update|publish|verify> [options]", "Team Pack lifecycle: share, install, sync, and verify a project .agent-shared/ pack. Team Pack is L2 — it never overwrites L1 Provider templates or L3 local overrides; receipt lives at .agent/team-sync/.team-receipt.json."),
  command("secrets", "secrets <store|verify|list|audit> [options]", "Store credential references through the project Secrets skill and verify provider access without printing secret values.", { mode: "credential_adapter", providers: ["npm"], plaintext_output: false }),
  command("help", "help [command] [--json]", "Show human or machine-readable CLI usage."),
  command("query", "query <projection> [filters]", "Query a project Management API and output JSON.", { mode: "read_only" }),
  command("task", "task <create|assign|accept|progress|heartbeat|test|ready|complete|block|request-input|cancel|takeover|status|list|watch> [options]", "Read or update Coordination Tasks through the Coordination Application Service."),
  command("event", "event <list|ack> [options]", "List coordination events or acknowledge delivery without changing task state."),
  command("lease", "lease <acquire|renew|release|status|recover> [options]", "Acquire and manage fenced task ownership leases through the durable Coordination LeaseManager. It never starts a host or creates a task.", { mode: "coordination_lease", restricted: true }),
  command("notification", "notification <pump> [options]", "Run, watch, inspect, or stop the Agent Coordination Notification Pump against an adapter whitelist. Never accepts event.command / event.executable from the CLI surface.", { mode: "adapter", thin: true, pending_integration: false }),
  command("runs", "runs <list|show|upsert|event|checkpoint|tokens>", "Read or update Run state through explicit actions."),
  command("queues", "queues <list|upsert|item>", "Read or update Queue state through explicit actions."),
  command("sessions", "sessions <list|open|heartbeat|pause|close>", "Read or update Session state through explicit actions."),
  command("session", "session <assess|log|checkpoint|archive|restore|resume-bundle|status|warm|host-switch|list-contexts>", "Manage agent session lifecycle and continuity (P-001; see docs/architecture/agent-runtime-continuity.md)."),
  command("decisions", "decisions <request|resolve|supersede>", "Use gated Decision lifecycle actions."),
  command("inbox", "inbox <send|transition>", "Use gated Inbox lifecycle actions."),
  command("waitpoints", "waitpoints <create|release|cancel>", "Use gated Waitpoint lifecycle actions."),
  command("mcp", "mcp serve --project <path>", "Start the read-only Management API MCP stdio server.", { mode: "read_only" }),
  command(
    "memory",
    "memory <recall|distill> [options]",
    "General-mode memory subsystem: cross-session distilled memories (episodic / semantic / procedural). `recall` is read-only with 0 mutation; `distill` writes .agent/memory/{type}/<id>.json with rollback on failure. Procedural write deferred to v1.12.",
    { mode: "general_memory", implemented: true, automatic_dispatch_enabled: false, requires: [".agent/memory/"] },
  ),
  command(
    "dispatch",
    "dispatch <subcommand> <task-id> [options]",
    "Governed manual dispatch with --dry-run support; execution is gated on approved_task + ownership_lease + idempotency_key + host + gate.",
    {
      mode: "governed_manual",
      implemented: true,
      automatic_dispatch_enabled: false,
      requires: ["approved_task", "ownership_lease", "idempotency_key", "host", "gate"],
    },
  ),
  command("daemon", "daemon <start|stop|status> [options]", "Reserved Phase 0 Daemon contract; background coordination is not implemented.", { mode: "phase0_stub", implemented: false, default_enabled: false }),
  command("trigger", "trigger <create|list|disable> [options]", "Reserved Phase 0 Trigger contract; trigger persistence is not implemented.", { mode: "phase0_stub", implemented: false }),
  command("dashboard", "dashboard <status|ensure|stop|auto> [options]", "Control the default-disabled project Dashboard Supervisor runtime.", { mode: "runtime_supervisor", default_enabled: false, mcp_writer: false }),
  command("dev", "dev [options]", "Start the live project dashboard."),
  command(
    "agent",
    "agent <discover|invoke|report|launch> ...",
    "Agent subsystem: discover/invoke = M-002 static capability registry (lib/agents/, read-only search + invocation plan); report/launch = M-008 coordination runtime (lib/commands.js, runtime lifecycle). Discover is read-only; invoke returns a deterministic plan (real execution lands in M-003 mission: 5 adapters + 1 MCP bridge). Report/launch use private launch identity; launch is one-shot and requires an already assigned task, matching active task lease/fencing token, explicit executable, and the same explicit allow-command. Repeat --agent-arg <value> for bounded explicit agent arguments; arguments stay private and no defaults are added. It never dispatches, daemons, reads credentials, pushes, or merges.",
    { mode: "split_registry", implemented: true, requires: [".agent/agents/"] },
  ),
  command("hook", "hook claude <HookName> [--stdin <json>]", "T-ACN-017-R4: Claude Code Hook Adapter — route hook events through the Agent Reporter. Use: cortex-agent hook claude <HookName> < bounded-stdin.json. Identity from CORTEX_LAUNCH_CONTEXT only. Governance fields in stdin are rejected. Supported hooks: SessionStart, PostToolUse, TestStart, Notification, Permission, ReadyForReview, Stop, SubagentStop.", { mode: "hook_cli", restricted: true }),
  command(
    "design",
    "design <list|install|upgrade|remove|show|resolved|refresh-catalog> [options]",
    "T-OD-001: Open Design integration — design system install/lockfile/4-level cascade. Content-addressed fetch from nexu-io/open-design upstream (Apache-2.0, 151 systems) with SHA-256 MITM protection, mandatory license ack, and a 4-level DESIGN.md cascade (<project>/DESIGN.md > <project>/.agent/DESIGN.md > install LIFO > cortex-agent starter). `list` defaults to installed; pass --available or --all to enumerate upstream catalog. `install` writes to <cwd>/.agent/design-systems/<id>/ and updates .agent/design-systems.lock. Exit codes: 0 success / 1 generic / 2 user error / 3 network / 4 license rejected.",
    { mode: "design_system", implemented: true, requires: [".agent/"], content_addressed: true }
  ),
  command("reconcile", "reconcile", "Reconcile MiniMax CLI governed-tool adapter state (ARI P-005 / M-011).", { mode: "governed_tool", restricted: true }),
  command("bridge", "bridge <sync|inbox|subscribe|unsubscribe|subscriptions|emit|outbox-list|outbox-prune|help> [options]", "Cross-Project Event Bridge (P-003 Phase 1 + P-006 producer side). Sync inbound bridge events from a source project's outbox into the local inbox, list the inbox, manage subscriptions, and emit outbound events to the local outbox. Writes stay under .agent-runtime/cross-project/ (Git-ignored).", { mode: "cross_project_bridge", phase: 1, scope: "consumer_and_producer" }),
  command(
    "automation",
    "automation <materialise-mission|emit-on-done|watch-inbox|approve-and-launch|help> [options]",
    "P-006 Cross-Project Automation Pipeline. materialise-mission scaffolds a mission directory + mission-plan.md + validation-contract.json from an approved proposal frontmatter; emit-on-done emits a bridge event for a completed mission per its bridge_emit gate; watch-inbox scans the inbox for a configured handler and writes dispatch sidecars under .agent/missions/<target>/; approve-and-launch is the materialise-mission alias used after proposal approval.",
    { mode: "cross_project_automation", implemented: true, requires: [".agent/bridges/", ".agent/missions/"] },
  ),
  command("topology", "topology <list|show|register|deregister|init|help> [options]", "Project Topology Registry (P-001 Phase A + P-001A self-id). Manage .agent/topology/projects.json — project identity, capabilities, and reachability for cross-project coordination. `init <project_id>` declares self-identity with --host-root.", { mode: "topology_registry", implemented: true, requires: [".agent/topology/"] }),
  command(
    "event-bus",
    "event-bus <publish|subscribe|list-events|history|resume> [options]",
    "M-004 / FAE-002: Framework event bus — 8 core events (subagent_spawned/progress/completed/failed/cancelled, handoff_ready, decision_resolved, waitpoint_released) + custom:* extensions. `publish` writes a single event; `subscribe` streams matching events to stdout (Ctrl-C to exit); `list-events` reads historical events; `history` returns events + acks + stats; `resume` lists the parent-resume client FSM active sub-agents for a --mission-id (--force lists awaiting escalation decisions). Persistence: pure JSONL at <bus-id>/events.jsonl (zero npm install). Exit codes: 0 success / 2 usage error / 3 runtime error.",
    { mode: "event_bus", implemented: true, requires: [".agent/event-bus/"] }
  ),
  command("branch", "branch <subcommand> [options]", "Git branch lifecycle management for cortex-agent-managed refs.", { mode: "branch_management" }),
  command("pr", "pr merge <pr-number> --gate user [options]", "Explicitly merge a pull request through the existing vcs-pr runtime. Never automatic; requires user gate.", { mode: "user_gated_vcs", implemented: true, automatic_merge_enabled: false, requires: [".agent/config/vcs.yml", "--gate user"] }),
  command("state-sync", "state-sync [--dry-run|--add|--commit|--push]", "Scan the state-class directories and stage/commit/push project-management state so it stays in lock-step across machines.", { mode: "state_sync" }),
];

const options = [
  { name: "--lang, -l <en|zh>", description: "Language, auto-detected by default." },
  { name: "--global, -g", description: "Use global ~/.agent configuration." },
  { name: "--project <path>", description: "Target an explicit project for management commands." },
  { name: "--since <date|time>", description: "Inclusive activity query start boundary." },
  { name: "--until <date|time>", description: "Inclusive activity query end boundary." },
  { name: "--track, -t", description: "Keep generated files in Git." },
  { name: "--platforms, -p <list>", description: "Select platforms non-interactively." },
  { name: "--update-scripts", description: "Apply safe managed-script updates during upgrade." },
  { name: "--force-scripts", description: "Overwrite locally modified managed scripts during update." },
  { name: "--dry-run", description: "Report upgrade/update changes without writing." },
  { name: "--report <text|json>", description: "Select update/upgrade report format." },
  { name: "--verify", description: "Run update verification without applying upgrade writes." },
  { name: "--verify-full", description: "Run heavier update verification checks." },
  { name: "--fix", description: "Apply doctor fixes, including forced script updates." },
  { name: "--team", description: "Opt in to Team Pack operations. Required on `init` (non-interactive) and `update` to engage .agent-shared/. Never valid on `upgrade` (additive-only) — use `update --team` for Team Pack sync." },
  { name: "--paths <path...>", description: "Explicit source paths for `team publish`. Required when promoting files to .agent-shared/." },
  { name: "--strict", description: "Run `team verify` / `doctor` in strict mode: manifest drift, schema mismatch, missing baselines, or unresolved conflicts become failures instead of warnings." },
  { name: "--ref <id>", description: "secrets: stable credential reference, exposed as secret://<id>." },
  { name: "--from-env <name>", description: "secrets store: read the value from an environment variable; public CLI intentionally rejects --value." },
  { name: "--provider <npm>", description: "secrets verify: provider whose authenticated identity is checked." },
  { name: "--registry <url>", description: "secrets verify: npm registry URL; defaults to https://registry.npmjs.org/." },
  { name: "--json", description: "Emit machine-readable output when supported, including help and Phase 0 stubs." },
  { name: "--consumer <id>", description: "notification pump: stable consumer identity used for cursor persistence and dedupe." },
  { name: "--target <kind:actorId>", description: "notification pump: required target selector. Format `<kind>:<actorId>`; both halves must come from the actor vocabulary." },
  { name: "--adapter <id>", description: "notification pump: whitelist adapter id. Accepted values: noop, claude-code, codex, webhook." },
  { name: "--once", description: "notification pump: run a single delivery pass and exit. Mutually exclusive with --watch|status|stop." },
  { name: "--watch", description: "notification pump: keep running until --stop or process signal. Mutually exclusive with --once|status|stop." },
  { name: "--status", description: "notification pump: report cursor state and exit. Mutually exclusive with --once|watch|stop." },
  { name: "--stop", description: "notification pump: stop a running watch loop and exit. Mutually exclusive with --once|watch|status." },
  { name: "--interval-ms <n>", description: "notification pump: minimum fallback interval in ms (1000..3600000). Default 1000; fs events wake it sooner." },
  { name: "--max-attempts <n>", description: "notification pump: override retry.maxAttempts (1..50). Default 5." },
  { name: "--event <id>", description: "notification pump: acknowledge a specific event id (used by adapter helpers, not the CLI surface)." },
];

const management = {
  project_scope: "Use --project explicitly for cross-project or worktree automation.",
  query: {
    usage: "cortex-agent query <projection> --project <path> [projection filters]",
    read_only: true,
    discovery: "cortex-agent help query --json --project <path>",
  },
  mcp: {
    usage: "cortex-agent mcp serve --project <path>",
    transport: "stdio",
    project_scope: "single_explicit_local_project",
    resources: "cortex://management/<projection>",
    tools: ["cortex.query"],
    writer_tools: false,
  },
  coordination: {
    projections: ["coordination-tasks", "coordination-events", "coordination-ownership", "coordination-notifications"],
    mcp_default: "read_only",
    writer_profile_default: false,
    writer_capabilities: [
      "coordination.task.create/assign",
      "coordination.task.transition",
      "coordination.task.heartbeat/complete",
      "coordination.task.cancel/takeover",
      "coordination.event.ack",
      "coordination.ownership.acquire/release",
    ],
    safety: "No arbitrary set_state capability; all writes delegate to the Coordination Application Service.",
  },
  writers: {
    runs: ["upsert", "event", "checkpoint", "tokens"],
    queues: ["upsert", "item"],
    sessions: ["open", "heartbeat", "pause", "close"],
    decisions: ["request", "resolve", "supersede"],
    inbox: ["send", "transition"],
    waitpoints: ["create", "release", "cancel"],
  },
  writer_usage: {
    "runs upsert": "cortex-agent runs upsert --project <path> --run-id <id> [run fields]",
    "runs event": "cortex-agent runs event --project <path> --run-id <id> --type <event> [event fields]",
    "runs checkpoint": "cortex-agent runs checkpoint --project <path> --run-id <id> --status <status> --phase <phase> [checkpoint fields]",
    "runs tokens": "cortex-agent runs tokens --project <path> --run-id <id> --source <host> --gate <workflow> [token fields]",
    "queues upsert": "cortex-agent queues upsert --project <path> --queue-id <id> --gate <workflow> [queue fields]",
    "queues item": "cortex-agent queues item --project <path> --queue-id <id> --task-id <id> --state <state> --gate <workflow> [item fields]",
    "sessions open": "cortex-agent sessions open --project <path> --session-id <id> --agent-id <id> --role <role> [session fields]",
    "sessions heartbeat": "cortex-agent sessions heartbeat --project <path> --session-id <id> --agent-id <owner> [session fields]",
    "sessions pause": "cortex-agent sessions pause --project <path> --session-id <id> --agent-id <owner> --gate <gate>",
    "sessions close": "cortex-agent sessions close --project <path> --session-id <id> --agent-id <owner> --gate <gate>",
    "decisions request": "cortex-agent decisions request --project <path> --decision-id <id> --gate <workflow> --type <type> --requested-by <id> --prompt <text> --action <action> --resource-ref <ref>",
    "decisions resolve": "cortex-agent decisions resolve --project <path> --decision-id <id> --gate user --status <status> --selected-option <option> --resolved-by <id> --rationale <text>",
    "decisions supersede": "cortex-agent decisions supersede --project <path> --decision-id <id> --gate requester --superseded-by-decision-id <id> --superseded-by <id> --rationale <text>",
    "inbox send": "cortex-agent inbox send --project <path> --message-id <id> --gate <workflow> --sender-id <id> --recipient-ids <ids> --subject <text>",
    "inbox transition": "cortex-agent inbox transition --project <path> --message-id <id> --gate <gate> --actor-id <id> --status <status>",
    "waitpoints create": "cortex-agent waitpoints create --project <path> --waitpoint-id <id> --gate <workflow> --owner-workflow <workflow> --reason <text> --action <action> --resource-ref <ref> --decision-id <id>",
    "waitpoints release": "cortex-agent waitpoints release --project <path> --waitpoint-id <id> --gate owner --owner-workflow <workflow> --decision-id <id> --released-by <id>",
    "waitpoints cancel": "cortex-agent waitpoints cancel --project <path> --waitpoint-id <id> --gate <gate> --owner-workflow <workflow> --reason <text>",
  },
  safety: [
    "No arbitrary write, state patch, shell execution, or executable automation action is exposed; Phase 0 dispatch, daemon, and trigger stubs are fail-closed and side-effect free.",
    "Writer actions remain subject to Management API gate, owner, Decision, Waitpoint, and lifecycle validation.",
    "Internal .agent script paths are implementation/debug fallbacks, not the standard Agent interface.",
  ],
};

const team = {
  project_scope: "Use --project explicitly for cross-project or worktree automation.",
  pack_layout: {
    pack_root: ".agent-shared/",
    manifest: ".agent-shared/team-pack.json",
    receipt_dir: ".agent/team-sync/",
    receipt_file: ".agent/team-sync/.team-receipt.json",
    baseline_dir: ".agent/team-sync/baselines/",
    report_dir: ".agent/team-sync/reports/",
    conflict_dir: ".agent/team-sync/conflicts/",
  },
  init: {
    usage: "cortex-agent team init [--project <path>] [--name <name>] [--team]",
    writes: [".agent-shared/"],
    interactive_default: "prompts whether to install the freshly discovered pack",
    non_interactive_default: "does not install unless --team is passed",
  },
  status: {
    usage: "cortex-agent team status [--project <path>] [--json]",
    read_only: true,
    compares: ["pack_manifest", "receipt", ".agent/"],
    reports: ["ahead", "behind", "conflict", "drift", "missing"],
  },
  install: {
    usage: "cortex-agent team install [--project <path>] [--dry-run] [--report text|json]",
    first_install_baseline: "empty (cold-start base must not be inferred from .agent/)",
    writes: [".agent/", ".agent/team-sync/.team-receipt.json"],
  },
  update: {
    usage: "cortex-agent team update [--project <path>] [--dry-run] [--report text|json]",
    merge_strategy: "three_way(base=receipt.baseline, local=.agent/, incoming=pack)",
    writes: [".agent/", ".agent/team-sync/.team-receipt.json", ".agent/team-sync/conflicts/"],
  },
  publish: {
    usage: "cortex-agent team publish --paths <path...> [--project <path>] [--dry-run]",
    requires_paths: true,
    writes: [".agent-shared/"],
    blocked_sources: [
      ".agent/",
      ".env",
      "**/*secret*",
      "**/*token*",
      "**/.claude/settings.json",
      "**/AGENTS.md",
      "**/CLAUDE.md",
      "**/GEMINI.md",
    ],
    side_effects: "never auto-commit, push, open PR, or modify protected branches",
  },
  verify: {
    usage: "cortex-agent team verify [--project <path>] [--strict] [--json]",
    read_only: true,
    checks: [
      "manifest_schema",
      "manifest_signature",
      "file_hash",
      "path_containment",
      "symlink_policy",
      "secret_scan",
      "absolute_path_scan",
      "receipt_baseline_present",
      "cortex_agent_version_compat",
    ],
  },
  boundary_with_update: {
    "update --team": "after L1 plan/apply succeeds, run Team Pack plan/apply; on L1 failure abort Team Pack step.",
    "upgrade --team": "rejected — `upgrade` is additive-only and never touches Team Pack.",
    "doctor --fix": "may repair deterministic Team Pack metadata (missing dirs, stale receipt fields) but must NOT publish, overwrite conflicts, or modify .agent-shared/.",
  },
  safety: [
    "All writes are confined to the resolved project root.",
    "Symlinks and hardlinks are rejected by default; writes use temp-file + atomic rename; eligible writes are backed up before overwrite.",
    "Secret, private-key header, token prefix, .env body, URL userinfo, and machine-absolute path scans fail closed; logs report rule + location only, never the matched value.",
    "publish refuses any path outside the fixed top-level allowlist; --force cannot bypass secret/path/credential detection.",
    "scripts shipped in .agent-shared/ are NOT authorization — execution still requires a Decision/Waitpoint per agent-workspace-orchestration.",
    "verify is read-only and CI-safe; publish must be triggered explicitly by the user or a protected maintainer workflow.",
  ],
};

const notification = {
  project_scope: "Use --project explicitly for cross-project or worktree automation.",
  scope: "Production Coordination notification pump. The CLI validates the public surface and delegates lifecycle, journal, cursor, and adapter work to the host harness in `lib/coordination/`.",
  contract_version: 1,
  pump: {
    usage: "cortex-agent notification pump --project <path> --consumer <id> --target <kind:actorId> --adapter <id> (--once | --watch | --status | --stop) [options]",
    required_flags: ["--project", "--consumer", "--target", "--adapter"],
    action_flags: {
      once: { flag: "--once", description: "Single delivery pass. Exits 0 on success, 3 on pump error.", exit_code: 0 },
      watch: { flag: "--watch", description: "Runs a persistent fs-event watch with bounded backoff until --stop or SIGINT/SIGTERM.", exit_code: 0 },
      status: { flag: "--status", description: "Reports cursor state without delivering. Always read-only and CI-safe.", exit_code: 0 },
      stop: { flag: "--stop", description: "Stops a running watch loop. Exits 0 even when no loop is found (idempotent).", exit_code: 0 },
    },
    action_exclusivity: "Exactly one of --once, --watch, --status, --stop is required. Passing zero or more than one is an INVALID_USAGE error (exit code 1).",
    adapter_whitelist: ["noop", "claude-code", "codex", "webhook"],
    options: {
      "--interval-ms": { min: 1000, max: 3600000, default: 1000 },
      "--max-attempts": { min: 1, max: 50, default: 5 },
    },
    exit_codes: {
      0: "success",
      1: "invalid usage",
      2: "unsupported",
      3: "runtime failure",
      4: "capability unavailable",
    },
  },
  cli_surface_limits: [
    "The CLI MUST NOT accept --event with a payload that contains event.command or event.executable.",
    "The CLI forwards ONLY a metadata envelope to the host adapter: eventId, projectId, taskId, target, consumerId, policy.",
    "Command construction / executable resolution stays inside the registered adapter module loaded by the host (e.g. lib/coordination/claude-adapter.js, lib/coordination/codex-adapter.js).",
    "All shell-out and runtime hooks live in the host-adapter layer; the CLI parses flags, validates whitelist, and delegates.",
  ],
  host_integration: {
    entry: "lib/coordination/notification-cli.js",
    thin_adapter: true,
    dependencies: {
      resolver: "injected by host process; resolves project root, consumer cursor store, journal, and adapter registry.",
      pump_factory: "injected; constructs NotificationPump from lib/coordination/notification-pump.js with the resolved adapter.",
      logger: "injected; defaults to { info, warn, error } writing to stdout/stderr.",
      codex_host: "official Codex App Server over stdio; target thread comes from CODEX_THREAD_ID or explicit CORTEX_CODEX_THREAD_ID.",
    },
    boundary: "lib/coordination/notification-cli.js MUST NOT require runtime modules from lib/coordination/application-service.js, lib/coordination/lease.js, or any concrete adapter file. lib/commands.js injects the production harness.",
  },
  safety: [
    "Adapter whitelist is enforced before any pump construction; unknown adapter ids are rejected with exit code 1.",
    "--target must match `kind:actorId` where kind ∈ {coordinator, agent, user, service, adapter} and actorId ∈ /^[A-Za-z0-9._:-]{1,128}$/.",
    "--consumer id must match /^[A-Za-z0-9._:-]{1,128}$/.",
    "All write operations stay inside the resolved project root; cursor files live under `.agent-runtime/coordination/consumers/<consumerId>.json`.",
    "The CLI does not call bash, exec, spawn, or any process invocation directly; it returns a structured result the host uses.",
  ],
  integration_notes: [
    "bin/cli.js dispatches `notification` through the exported commands.js shim; integrators do NOT directly require the CLI entry point.",
    "lib/commands.js wires lib/coordination/notification-cli.js to the project-scoped production harness, journal reader, cursor store, runtime supervisor, and registered adapter.",
    "The Codex adapter initializes the official app-server protocol, resumes the target thread, starts a bounded notification turn, and reports delivered only after that real turn completes.",
    "The thin adapter is dependency-injected; tests pass a stub resolver/factory and assert exit codes and the parsed payload without touching the real journal or filesystem.",
    "If the host process is the Agent Dashboard or the team-pack runtime, the same adapter is reused — only the resolver changes.",
  ],
};

module.exports = {
  schema_version: 1,
  discovery_command: "cortex-agent help --json",
  commands,
  options,
  management,
  team,
  notification,
};
