"use strict";

const PROTOCOL_NAME = "cortex";
const PROTOCOL_VERSION = "1.0";
const RUNTIME_PROTOCOL_NAME = "cortex-runtime";
const RUNTIME_PROTOCOL_VERSION = "1.0";
const PROJECT_PROTOCOL_NAME = "cortex-project";
const PROJECT_PROTOCOL_VERSION = "1.0";

module.exports = {
  PROTOCOL_NAME,
  PROTOCOL_VERSION,
  RUNTIME_PROTOCOL_NAME,
  RUNTIME_PROTOCOL_VERSION,
  PROJECT_PROTOCOL_NAME,
  PROJECT_PROTOCOL_VERSION,
};
