"use strict";

// ─── md-deck — zero-dep Markdown deck summary ────────────────────────────────
//
// P-003 /deck: produces a Markdown summary suitable for README / speaker notes
// / GitHub issue attachment. Each slide becomes a section with H2 title +
// bullets / body. Speaker notes flow into a separate block.

function escapePipe(value) {
  // Pipe within tables needs escaping — keep this safe for table rendering.
  return String(value ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");
}

/**
 * Build a Markdown summary from slide specs.
 * @param {{ slides: Array<object>, meta?: object }} opts
 * @returns {string}
 */
function buildMdDeck(opts) {
  const slides = Array.isArray(opts && opts.slides) ? opts.slides : [];
  if (slides.length === 0) {
    throw new Error("buildMdDeck: at least one slide is required");
  }
  const meta = (opts && opts.meta) || {};

  const lines = [];
  lines.push(`# ${meta.title || "Deck"}`);
  if (meta.author) lines.push("");
  if (meta.author) lines.push(`> Author: ${meta.author}`);
  if (meta.subject) lines.push(`> Subject: ${meta.subject}`);
  lines.push("");
  lines.push(`_Generated by cortex-agent / P-003 /deck on ${new Date().toISOString().slice(0, 10)}._`);
  lines.push("");
  lines.push(`Total slides: ${slides.length}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  slides.forEach((slide, i) => {
    lines.push(`## ${i + 1}. ${slide.title || "Untitled"}`);
    lines.push("");
    if (slide.subtitle) {
      lines.push(`*${slide.subtitle}*`);
      lines.push("");
    }
    if (Array.isArray(slide.bullets) && slide.bullets.length > 0) {
      for (const b of slide.bullets) {
        lines.push(`- ${b}`);
      }
      lines.push("");
    }
    if (slide.body) {
      lines.push(slide.body);
      lines.push("");
    }
    if (slide.notes) {
      lines.push(`> **Speaker notes:** ${slide.notes}`);
      lines.push("");
    }
    lines.push("---");
    lines.push("");
  });

  return lines.join("\n");
}

module.exports = {
  buildMdDeck,
};